#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/METHODS/FALSEHYP/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'falsehyptheory1.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'falsehyp8.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'falsehyp3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'falsehyp4.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'falsehyp5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'falsehyp12.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: true, category: 'home', order: 4, file_id: p.id)
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'falsehyptheory2.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 2, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'falsehyp6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'falsehyp7.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'falsehyp9.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'falsehyp11.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 3, file_id: p.id)
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'falsehyptheory3.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 4, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'falsehyp1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'falsehyp2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'falsehyp14.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'falsehyp13.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 3, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/METHODS/CASETRY/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'casetrytheory1.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'casetry1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'casetry6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'casetry3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'casetry9.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'casetry5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'casetry7.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'casetry8.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 6, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'casetry2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 7, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'casetry4.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 8, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/METHODS/BACKWARDS/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'backwardstheory1.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'backwards3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'backwards1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 1, file_id: p.id)
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'backwardstheory2.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 2, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'backwards2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'backwards5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'backwards4.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'backwards6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: true, category: 'home', order: 3, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/METHODS/comparison/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'comparisontheory1.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'comparison4.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'comparison6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'comparison5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'comparison2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'comparison7.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'comparison3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'comparison1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 3, file_id: p.id)
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'comparisontheory2.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 3, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'comparison10.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'comparison9.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'comparison8.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'comparison11.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'comparison12.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'comparison13.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: true, category: 'home', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'comparison14.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'comparison15.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 1, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/METHODS/PROPORTIONS/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'proportionstheory1.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions22.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 1, file_id: p.id)
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'proportionstheory2.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 2, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions10.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions12.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 2, file_id: p.id)
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'proportionstheory3.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 4, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions9.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 2, file_id: p.id)
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'proportionstheory4.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 6, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions14.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions7.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions15.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions23.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 4, file_id: p.id)
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'proportionstheory5.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 8, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions16.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 9, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions17.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 9, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions18.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 9, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions19.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 9, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions20.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 9, makeup: false, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions21.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 9, makeup: false, category: 'home', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'proportions24.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 9, makeup: false, category: 'home', order: 6, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/METHODS/NUMERICAL/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'numericaltheory.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'numerical4.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'numerical2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'numerical3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'numerical5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: true, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'numerical1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'numerical6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: true, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'numerical7.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'numerical8.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 1, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/METHODS/GRAPHICAL/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'graphicaltheory1.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'graphical1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'graphical4.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 1, file_id: p.id)
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'graphicaltheory2.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 2, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'graphical2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'graphical3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 1, file_id: p.id)
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'graphicaltheory3.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 4, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'graphical5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'graphical6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 1, file_id: p.id)
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'graphicaltheory4.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 6, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'graphical7.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'graphical8.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 1, file_id: p.id)
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'graphicaltheory5.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 8, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'graphical9.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 9, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'graphical10.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 9, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'graphical11.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 9, makeup: false, category: 'home', order: 2, file_id: p.id)
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'graphicaltheory6.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 10, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'graphical12.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 11, makeup: false, category: 'home', order: 0, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/APPLICATIONS/LIQUIDS/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'liquidtheory.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid4.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid13.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid15.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: true, category: 'home', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid17.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid18.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid7.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid8.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid14.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid9.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid10.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid11.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'liquid16.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 0, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/APPLICATIONS/QUANTITIES/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'quantitytheory.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity7.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity4.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity21.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity8.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity22.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: true, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity9.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity11.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity12.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity14.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity28.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: true, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity10.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity27.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity19.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity24.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: true, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity26.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity25.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity23.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity17.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity16.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity20.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'quantity18.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 3, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/APPLICATIONS/MOTION/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'motiontheory.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion8.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion9.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion26.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: true, category: 'home', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion10.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion14.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion27.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion21.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion32.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion33.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion4.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion28.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: true, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion11.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion12.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion30.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion20.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion13.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion29.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion15.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion16.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion17.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion18.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion19.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion31.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: true, category: 'home', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion22.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 8, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion23.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 8, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion24.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 8, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion34.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 8, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion35.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 8, makeup: false, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'motion25.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 8, makeup: false, category: 'home', order: 5, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/APPLICATIONS/PERCENTAGES/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'percentagetheory.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage26.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: true, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage8.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage4.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage34.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: true, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage7.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage35.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage27.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: true, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage9.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage14.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage31.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage20.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage28.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: true, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage17.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage10.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage11.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage12.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage13.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage29.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: true, category: 'home', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage18.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage19.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage21.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage32.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage33.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage30.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: true, category: 'home', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage15.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage16.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage22.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage25.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'percentage24.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: true, category: 'home', order: 4, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/APPLICATIONS/MONEY/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'moneytheory.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money20.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: true, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money4.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money21.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money22.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money7.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money8.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money23.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money9.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money24.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: true, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money10.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money28.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money11.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 8, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money25.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 8, makeup: true, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money12.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 9, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money13.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 9, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money14.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 9, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money26.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 9, makeup: true, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money27.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 10, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money19.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 10, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money16.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 10, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money17.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 10, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'money18.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 10, makeup: false, category: 'home', order: 4, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/APPLICATIONS/TIME/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'timetheory.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time13.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time18.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time4.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time7.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time14.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: true, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time19.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time8.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time20.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time9.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time15.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 7, makeup: true, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time17.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 8, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time10.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 8, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time11.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 8, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time12.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 8, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time16.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 8, makeup: true, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'time21.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 9, makeup: false, category: 'home', order: 0, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/APPLICATIONS/AVERAGE/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'averagetheory.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'average4.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'average5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'average6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'average12.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'average10.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: true, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'average1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'average3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'average14.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'average13.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: true, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'average7.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'average8.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'average9.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'average2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'average11.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'average15.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: true, category: 'home', order: 2, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/ALGEBRAIC/ONEVAR/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'onevartheory1.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'onevartheory2.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 1, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar23.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar12.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar19.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar25.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar18.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar22.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: true, category: 'home', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar14.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar20.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar21.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar4.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar9.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar15.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: true, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar16.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar7.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar26.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar8.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar10.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar11.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar17.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: true, category: 'home', order: 6, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar13.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'onevar24.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 2, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/ALGEBRAIC/CANCEL/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'canceltheory.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel14.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel9.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel7.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel4.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel15.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: true, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel8.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel13.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel17.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel16.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: true, category: 'home', order: 6, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel10.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel12.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'cancel11.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 4, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/ALGEBRAIC/MOREVAR/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'morevartheory1.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'morevartheory2.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 1, category: 'home')
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar10.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar3.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar8.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar11.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar21.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: false, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar16.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 1, makeup: true, category: 'home', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar6.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar7.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar9.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar18.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar20.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: false, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar19.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 2, makeup: true, category: 'home', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar14.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar12.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar15.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 3, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar4.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar25.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar26.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar2.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: false, category: 'home', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar13.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 4, makeup: true, category: 'home', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar22.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar24.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar23.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 5, makeup: true, category: 'home', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar17.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar5.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'home', context: 'lancaster', filename: 'morevar1.html')
Graph.create!(typ: 'prob', context: 'lancaster', batch: 6, makeup: false, category: 'home', order: 2, file_id: p.id)
#GRAPH TUPLES FROM /home/lancaster/Documents/persProj/ma_files/LIFETOMATH/INTRODUCTION/EXAMPLES/graph.txt
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'exampletheory1.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'home')
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'exampletheory2.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 1, category: 'home')
t = Theory.find_by!(category: 'home', context: 'lancaster', filename: 'exampletheory3.html')
Graph.create!(typ: 'theory', context: 'lancaster', batch: 0, file_id: t.id, makeup: false, order: 2, category: 'home')
