#GRAPH TUPLES FROM ./METHODS/FALSEHYP/graph.txt
Graph.create!(typ: 'theory', context: './METHODS/FALSEHYP/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './METHODS/FALSEHYP/falsehyp8.html')
Graph.create!(typ: 'prob', context: './METHODS/FALSEHYP/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/FALSEHYP/falsehyp3.html')
Graph.create!(typ: 'prob', context: './METHODS/FALSEHYP/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/FALSEHYP/falsehyp4.html')
Graph.create!(typ: 'prob', context: './METHODS/FALSEHYP/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/FALSEHYP/falsehyp5.html')
Graph.create!(typ: 'prob', context: './METHODS/FALSEHYP/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/FALSEHYP/falsehyp12.html')
Graph.create!(typ: 'prob', context: './METHODS/FALSEHYP/', batch: 1, makeup: True, file_id: p.id)
Graph.create!(typ: 'theory', context: './METHODS/FALSEHYP/', batch: 2, file_id: 0)
p = Problem.find_by(filename: './METHODS/FALSEHYP/falsehyp6.html')
Graph.create!(typ: 'prob', context: './METHODS/FALSEHYP/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/FALSEHYP/falsehyp7.html')
Graph.create!(typ: 'prob', context: './METHODS/FALSEHYP/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/FALSEHYP/falsehyp9.html')
Graph.create!(typ: 'prob', context: './METHODS/FALSEHYP/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/FALSEHYP/falsehyp11.html')
Graph.create!(typ: 'prob', context: './METHODS/FALSEHYP/', batch: 3, makeup: False, file_id: p.id)
Graph.create!(typ: 'theory', context: './METHODS/FALSEHYP/', batch: 4, file_id: 0)
p = Problem.find_by(filename: './METHODS/FALSEHYP/falsehyp1.html')
Graph.create!(typ: 'prob', context: './METHODS/FALSEHYP/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/FALSEHYP/falsehyp2.html')
Graph.create!(typ: 'prob', context: './METHODS/FALSEHYP/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/FALSEHYP/falsehyp14.html')
Graph.create!(typ: 'prob', context: './METHODS/FALSEHYP/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/FALSEHYP/falsehyp13.html')
Graph.create!(typ: 'prob', context: './METHODS/FALSEHYP/', batch: 5, makeup: False, file_id: p.id)
#GRAPH TUPLES FROM ./METHODS/CASETRY/graph.txt
Graph.create!(typ: 'theory', context: './METHODS/CASETRY/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './METHODS/CASETRY/casetry1.html')
Graph.create!(typ: 'prob', context: './METHODS/CASETRY/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/CASETRY/casetry6.html')
Graph.create!(typ: 'prob', context: './METHODS/CASETRY/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/CASETRY/casetry3.html')
Graph.create!(typ: 'prob', context: './METHODS/CASETRY/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/CASETRY/casetry9.html')
Graph.create!(typ: 'prob', context: './METHODS/CASETRY/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/CASETRY/casetry5.html')
Graph.create!(typ: 'prob', context: './METHODS/CASETRY/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/CASETRY/casetry7.html')
Graph.create!(typ: 'prob', context: './METHODS/CASETRY/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/CASETRY/casetry8.html')
Graph.create!(typ: 'prob', context: './METHODS/CASETRY/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/CASETRY/casetry2.html')
Graph.create!(typ: 'prob', context: './METHODS/CASETRY/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/CASETRY/casetry4.html')
Graph.create!(typ: 'prob', context: './METHODS/CASETRY/', batch: 1, makeup: False, file_id: p.id)
#GRAPH TUPLES FROM ./METHODS/BACKWARDS/graph.txt
Graph.create!(typ: 'theory', context: './METHODS/BACKWARDS/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './METHODS/BACKWARDS/backwards1.html')
Graph.create!(typ: 'prob', context: './METHODS/BACKWARDS/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/BACKWARDS/backwards3.html')
Graph.create!(typ: 'prob', context: './METHODS/BACKWARDS/', batch: 1, makeup: False, file_id: p.id)
Graph.create!(typ: 'theory', context: './METHODS/BACKWARDS/', batch: 2, file_id: 0)
p = Problem.find_by(filename: './METHODS/BACKWARDS/backwards2.html')
Graph.create!(typ: 'prob', context: './METHODS/BACKWARDS/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/BACKWARDS/backwards5.html')
Graph.create!(typ: 'prob', context: './METHODS/BACKWARDS/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/BACKWARDS/backwards4.html')
Graph.create!(typ: 'prob', context: './METHODS/BACKWARDS/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/BACKWARDS/backwards6.html')
Graph.create!(typ: 'prob', context: './METHODS/BACKWARDS/', batch: 3, makeup: True, file_id: p.id)
#GRAPH TUPLES FROM ./METHODS/comparison/graph.txt
Graph.create!(typ: 'theory', context: './METHODS/comparison/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './METHODS/comparison/comparison4.html')
Graph.create!(typ: 'prob', context: './METHODS/comparison/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/comparison/comparison6.html')
Graph.create!(typ: 'prob', context: './METHODS/comparison/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/comparison/comparison5.html')
Graph.create!(typ: 'prob', context: './METHODS/comparison/', batch: 1, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './METHODS/comparison/comparison2.html')
Graph.create!(typ: 'prob', context: './METHODS/comparison/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/comparison/comparison7.html')
Graph.create!(typ: 'prob', context: './METHODS/comparison/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/comparison/comparison3.html')
Graph.create!(typ: 'prob', context: './METHODS/comparison/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/comparison/comparison1.html')
Graph.create!(typ: 'prob', context: './METHODS/comparison/', batch: 2, makeup: False, file_id: p.id)
Graph.create!(typ: 'theory', context: './METHODS/comparison/', batch: 3, file_id: 0)
p = Problem.find_by(filename: './METHODS/comparison/comparison10.html')
Graph.create!(typ: 'prob', context: './METHODS/comparison/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/comparison/comparison9.html')
Graph.create!(typ: 'prob', context: './METHODS/comparison/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/comparison/comparison8.html')
Graph.create!(typ: 'prob', context: './METHODS/comparison/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/comparison/comparison11.html')
Graph.create!(typ: 'prob', context: './METHODS/comparison/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/comparison/comparison12.html')
Graph.create!(typ: 'prob', context: './METHODS/comparison/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/comparison/comparison13.html')
Graph.create!(typ: 'prob', context: './METHODS/comparison/', batch: 4, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './METHODS/comparison/comparison14.html')
Graph.create!(typ: 'prob', context: './METHODS/comparison/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/comparison/comparison15.html')
Graph.create!(typ: 'prob', context: './METHODS/comparison/', batch: 5, makeup: False, file_id: p.id)
#GRAPH TUPLES FROM ./METHODS/PROPORTIONS/graph.txt
Graph.create!(typ: 'theory', context: './METHODS/PROPORTIONS/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions1.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions2.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions3.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 1, makeup: False, file_id: p.id)
Graph.create!(typ: 'theory', context: './METHODS/PROPORTIONS/', batch: 3, file_id: 0)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions5.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions10.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions12.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 4, makeup: False, file_id: p.id)
Graph.create!(typ: 'theory', context: './METHODS/PROPORTIONS/', batch: 5, file_id: 0)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions9.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 6, makeup: False, file_id: p.id)
Graph.create!(typ: 'theory', context: './METHODS/PROPORTIONS/', batch: 7, file_id: 0)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions14.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions6.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions7.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions15.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions23.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 8, makeup: False, file_id: p.id)
Graph.create!(typ: 'theory', context: './METHODS/PROPORTIONS/', batch: 9, file_id: 0)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions16.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 10, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions17.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 10, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions18.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 10, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions19.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 10, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions20.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 10, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions21.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 10, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/PROPORTIONS/proportions24.html')
Graph.create!(typ: 'prob', context: './METHODS/PROPORTIONS/', batch: 10, makeup: False, file_id: p.id)
#GRAPH TUPLES FROM ./METHODS/NUMERICAL/graph.txt
Graph.create!(typ: 'theory', context: './METHODS/NUMERICAL/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './METHODS/NUMERICAL/numerical4.html')
Graph.create!(typ: 'prob', context: './METHODS/NUMERICAL/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/NUMERICAL/numerical2.html')
Graph.create!(typ: 'prob', context: './METHODS/NUMERICAL/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/NUMERICAL/numerical3.html')
Graph.create!(typ: 'prob', context: './METHODS/NUMERICAL/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/NUMERICAL/numerical5.html')
Graph.create!(typ: 'prob', context: './METHODS/NUMERICAL/', batch: 1, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './METHODS/NUMERICAL/numerical1.html')
Graph.create!(typ: 'prob', context: './METHODS/NUMERICAL/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/NUMERICAL/numerical6.html')
Graph.create!(typ: 'prob', context: './METHODS/NUMERICAL/', batch: 2, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './METHODS/NUMERICAL/numerical7.html')
Graph.create!(typ: 'prob', context: './METHODS/NUMERICAL/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/NUMERICAL/numerical8.html')
Graph.create!(typ: 'prob', context: './METHODS/NUMERICAL/', batch: 3, makeup: False, file_id: p.id)
#GRAPH TUPLES FROM ./METHODS/GRAPHICAL/graph.txt
Graph.create!(typ: 'theory', context: './METHODS/GRAPHICAL/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './METHODS/GRAPHICAL/graphical1.html')
Graph.create!(typ: 'prob', context: './METHODS/GRAPHICAL/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/GRAPHICAL/graphical4.html')
Graph.create!(typ: 'prob', context: './METHODS/GRAPHICAL/', batch: 1, makeup: False, file_id: p.id)
Graph.create!(typ: 'theory', context: './METHODS/GRAPHICAL/', batch: 2, file_id: 0)
p = Problem.find_by(filename: './METHODS/GRAPHICAL/graphical2.html')
Graph.create!(typ: 'prob', context: './METHODS/GRAPHICAL/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/GRAPHICAL/graphical3.html')
Graph.create!(typ: 'prob', context: './METHODS/GRAPHICAL/', batch: 3, makeup: False, file_id: p.id)
Graph.create!(typ: 'theory', context: './METHODS/GRAPHICAL/', batch: 4, file_id: 0)
p = Problem.find_by(filename: './METHODS/GRAPHICAL/graphical5.html')
Graph.create!(typ: 'prob', context: './METHODS/GRAPHICAL/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/GRAPHICAL/graphical6.html')
Graph.create!(typ: 'prob', context: './METHODS/GRAPHICAL/', batch: 5, makeup: False, file_id: p.id)
Graph.create!(typ: 'theory', context: './METHODS/GRAPHICAL/', batch: 6, file_id: 0)
p = Problem.find_by(filename: './METHODS/GRAPHICAL/graphical7.html')
Graph.create!(typ: 'prob', context: './METHODS/GRAPHICAL/', batch: 7, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/GRAPHICAL/graphical8.html')
Graph.create!(typ: 'prob', context: './METHODS/GRAPHICAL/', batch: 7, makeup: False, file_id: p.id)
Graph.create!(typ: 'theory', context: './METHODS/GRAPHICAL/', batch: 8, file_id: 0)
p = Problem.find_by(filename: './METHODS/GRAPHICAL/graphical9.html')
Graph.create!(typ: 'prob', context: './METHODS/GRAPHICAL/', batch: 9, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/GRAPHICAL/graphical10.html')
Graph.create!(typ: 'prob', context: './METHODS/GRAPHICAL/', batch: 9, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './METHODS/GRAPHICAL/graphical11.html')
Graph.create!(typ: 'prob', context: './METHODS/GRAPHICAL/', batch: 9, makeup: False, file_id: p.id)
Graph.create!(typ: 'theory', context: './METHODS/GRAPHICAL/', batch: 10, file_id: 0)
p = Problem.find_by(filename: './METHODS/GRAPHICAL/graphical12.html')
Graph.create!(typ: 'prob', context: './METHODS/GRAPHICAL/', batch: 11, makeup: False, file_id: p.id)
#GRAPH TUPLES FROM ./APPLICATIONS/LIQUIDS/graph.txt
Graph.create!(typ: 'theory', context: './APPLICATIONS/LIQUIDS/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid1.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid2.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid3.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid4.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid5.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid6.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid13.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid15.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 2, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid17.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid18.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid7.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid8.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid14.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 4, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid9.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid10.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid11.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 5, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/LIQUIDS/liquid16.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/LIQUIDS/', batch: 6, makeup: False, file_id: p.id)
#GRAPH TUPLES FROM ./APPLICATIONS/QUANTITIES/graph.txt
Graph.create!(typ: 'theory', context: './APPLICATIONS/QUANTITIES/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity7.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity1.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity4.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 1, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity5.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity2.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity3.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity6.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity21.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity8.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity22.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 4, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity9.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity11.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity12.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity14.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity28.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 5, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity10.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity27.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity19.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity24.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 6, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity26.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 7, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity25.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 7, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity23.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 7, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity17.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity16.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity20.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/QUANTITIES/quantity18.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/QUANTITIES/', batch: 8, makeup: False, file_id: p.id)
#GRAPH TUPLES FROM ./APPLICATIONS/MOTION/graph.txt
Graph.create!(typ: 'theory', context: './APPLICATIONS/MOTION/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion2.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion8.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion1.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion6.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion9.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion26.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 1, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion10.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion14.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion27.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 2, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion21.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion32.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion33.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 3, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion3.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion4.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion5.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion28.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 4, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion11.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion12.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion30.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 5, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion20.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion13.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion29.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 6, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion15.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 7, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion16.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 7, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion17.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 7, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion18.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 7, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion19.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 7, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion31.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 7, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion22.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion23.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion24.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion34.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion35.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MOTION/motion25.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MOTION/', batch: 8, makeup: False, file_id: p.id)
#GRAPH TUPLES FROM ./APPLICATIONS/PERCENTAGES/graph.txt
Graph.create!(typ: 'theory', context: './APPLICATIONS/PERCENTAGES/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage1.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage2.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage5.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage26.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 1, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage8.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage4.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage3.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage34.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 2, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage6.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage7.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage35.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage27.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 3, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage9.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage14.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage31.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage20.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage28.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 4, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage17.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage10.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage11.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage12.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage13.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage29.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 5, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage18.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage19.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage21.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage32.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage33.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage30.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 6, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage15.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 7, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage16.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 7, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage22.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 7, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage25.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 7, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/PERCENTAGES/percentage24.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/PERCENTAGES/', batch: 7, makeup: True, file_id: p.id)
#GRAPH TUPLES FROM ./APPLICATIONS/MONEY/graph.txt
Graph.create!(typ: 'theory', context: './APPLICATIONS/MONEY/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money2.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money20.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 1, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money1.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money3.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money4.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money21.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 3, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money5.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money6.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money22.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 4, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money7.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money8.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money23.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 5, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money9.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money24.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 6, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money10.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 7, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money28.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 7, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money11.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money25.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 8, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money12.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 9, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money13.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 9, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money14.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 9, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money26.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 9, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money27.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 10, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money19.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 10, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money16.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 10, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money17.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 10, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/MONEY/money18.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/MONEY/', batch: 10, makeup: False, file_id: p.id)
#GRAPH TUPLES FROM ./APPLICATIONS/TIME/graph.txt
Graph.create!(typ: 'theory', context: './APPLICATIONS/TIME/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time1.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time3.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time2.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time13.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 2, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time18.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time4.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time5.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time7.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time14.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 4, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time6.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time19.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time8.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time20.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 6, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time9.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 7, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time15.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 7, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time17.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time10.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time11.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time12.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 8, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time16.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 8, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/TIME/time21.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/TIME/', batch: 9, makeup: False, file_id: p.id)
#GRAPH TUPLES FROM ./APPLICATIONS/AVERAGE/graph.txt
Graph.create!(typ: 'theory', context: './APPLICATIONS/AVERAGE/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './APPLICATIONS/AVERAGE/average4.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/AVERAGE/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/AVERAGE/average5.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/AVERAGE/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/AVERAGE/average6.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/AVERAGE/', batch: 1, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/AVERAGE/average12.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/AVERAGE/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/AVERAGE/average10.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/AVERAGE/', batch: 2, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/AVERAGE/average1.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/AVERAGE/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/AVERAGE/average3.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/AVERAGE/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/AVERAGE/average14.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/AVERAGE/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/AVERAGE/average13.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/AVERAGE/', batch: 3, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/AVERAGE/average7.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/AVERAGE/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/AVERAGE/average8.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/AVERAGE/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/AVERAGE/average9.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/AVERAGE/', batch: 4, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/AVERAGE/average2.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/AVERAGE/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/AVERAGE/average11.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/AVERAGE/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './APPLICATIONS/AVERAGE/average15.html')
Graph.create!(typ: 'prob', context: './APPLICATIONS/AVERAGE/', batch: 5, makeup: True, file_id: p.id)
#GRAPH TUPLES FROM ./ALGEBRAIC/ONEVAR/graph.txt
Graph.create!(typ: 'theory', context: './ALGEBRAIC/ONEVAR/', batch: 0, file_id: 0)
Graph.create!(typ: 'theory', context: './ALGEBRAIC/ONEVAR/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar23.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar12.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar19.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar25.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar18.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar22.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 1, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar14.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar20.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar21.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 2, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar5.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar4.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar9.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar15.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 3, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar3.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar6.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar16.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 4, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar1.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar7.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar26.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar8.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar10.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar11.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar17.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 5, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar2.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar13.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/ONEVAR/onevar24.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/ONEVAR/', batch: 6, makeup: False, file_id: p.id)
#GRAPH TUPLES FROM ./ALGEBRAIC/CANCEL/graph.txt
Graph.create!(typ: 'theory', context: './ALGEBRAIC/CANCEL/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel14.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel9.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel7.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel4.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel15.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 1, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel8.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel3.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel5.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel6.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel13.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel17.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel16.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 2, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel10.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel2.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel1.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel12.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/CANCEL/cancel11.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/CANCEL/', batch: 3, makeup: False, file_id: p.id)
#GRAPH TUPLES FROM ./ALGEBRAIC/MOREVAR/graph.txt
Graph.create!(typ: 'theory', context: './ALGEBRAIC/MOREVAR/', batch: 0, file_id: 0)
Graph.create!(typ: 'theory', context: './ALGEBRAIC/MOREVAR/', batch: 0, file_id: 0)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar10.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar3.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar8.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar11.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar21.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 1, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar16.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 1, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar6.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar7.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar9.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar18.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar20.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 2, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar19.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 2, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar14.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar12.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 3, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar15.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 3, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar4.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar25.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar26.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar2.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 4, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar13.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 4, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar22.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar24.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 5, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar23.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 5, makeup: True, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar17.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar5.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 6, makeup: False, file_id: p.id)
p = Problem.find_by(filename: './ALGEBRAIC/MOREVAR/morevar1.html')
Graph.create!(typ: 'prob', context: './ALGEBRAIC/MOREVAR/', batch: 6, makeup: False, file_id: p.id)
