#GRAPH TUPLES FROM ./APPLICATIONS/LIQUIDS/graph.txt
t = Theory.find_by!(category: 'applications', context: 'liquids', filename: 'liquidtheory.html')
Graph.create!(typ: 'theory', context: 'liquids', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'applications')
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid1.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 1, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid2.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 1, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid3.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 2, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid4.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 2, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid5.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 2, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid6.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 2, makeup: false, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid13.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 2, makeup: false, category: 'applications', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid15.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 2, makeup: true, category: 'applications', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid17.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 3, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid18.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 3, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid7.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 4, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid8.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 4, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid14.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 4, makeup: true, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid9.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 5, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid10.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 5, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid11.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 5, makeup: true, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'liquids', filename: 'liquid16.html')
Graph.create!(typ: 'prob', context: 'liquids', batch: 6, makeup: false, category: 'applications', order: 0, file_id: p.id)
#GRAPH TUPLES FROM ./APPLICATIONS/QUANTITIES/graph.txt
t = Theory.find_by!(category: 'applications', context: 'quantities', filename: 'quantitytheory.html')
Graph.create!(typ: 'theory', context: 'quantities', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'applications')
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity7.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 1, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity1.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 1, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity4.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 1, makeup: true, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity5.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 2, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity2.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 2, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity3.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 2, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity6.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 4, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity21.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 4, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity8.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 4, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity22.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 4, makeup: true, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity9.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 5, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity11.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 5, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity12.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 5, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity14.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 5, makeup: false, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity28.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 5, makeup: true, category: 'applications', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity10.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 6, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity27.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 6, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity19.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 6, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity24.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 6, makeup: true, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity26.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 7, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity25.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 7, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity23.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 7, makeup: true, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity17.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 8, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity16.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 8, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity20.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 8, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'quantities', filename: 'quantity18.html')
Graph.create!(typ: 'prob', context: 'quantities', batch: 8, makeup: false, category: 'applications', order: 3, file_id: p.id)
#GRAPH TUPLES FROM ./APPLICATIONS/MOTION/graph.txt
t = Theory.find_by!(category: 'applications', context: 'motion', filename: 'motiontheory.html')
Graph.create!(typ: 'theory', context: 'motion', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'applications')
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion2.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 1, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion8.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 1, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion1.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 1, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion6.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 1, makeup: false, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion9.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 1, makeup: false, category: 'applications', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion26.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 1, makeup: true, category: 'applications', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion10.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 2, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion14.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 2, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion27.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 2, makeup: true, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion21.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 3, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion32.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 3, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion33.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 3, makeup: true, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion3.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 4, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion4.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 4, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion5.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 4, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion28.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 4, makeup: true, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion11.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 5, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion12.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 5, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion30.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 5, makeup: true, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion20.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 6, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion13.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 6, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion29.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 6, makeup: true, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion15.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 7, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion16.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 7, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion17.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 7, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion18.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 7, makeup: false, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion19.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 7, makeup: false, category: 'applications', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion31.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 7, makeup: true, category: 'applications', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion22.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 8, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion23.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 8, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion24.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 8, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion34.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 8, makeup: false, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion35.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 8, makeup: false, category: 'applications', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'motion', filename: 'motion25.html')
Graph.create!(typ: 'prob', context: 'motion', batch: 8, makeup: false, category: 'applications', order: 5, file_id: p.id)
#GRAPH TUPLES FROM ./APPLICATIONS/PERCENTAGES/graph.txt
t = Theory.find_by!(category: 'applications', context: 'percentages', filename: 'percentagetheory.html')
Graph.create!(typ: 'theory', context: 'percentages', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'applications')
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage1.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 1, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage2.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 1, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage5.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 1, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage26.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 1, makeup: true, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage8.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 2, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage4.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 2, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage3.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 2, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage34.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 2, makeup: true, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage6.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 3, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage7.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 3, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage35.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 3, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage27.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 3, makeup: true, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage9.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 4, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage14.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 4, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage31.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 4, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage20.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 4, makeup: false, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage28.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 4, makeup: true, category: 'applications', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage17.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 5, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage10.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 5, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage11.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 5, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage12.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 5, makeup: false, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage13.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 5, makeup: false, category: 'applications', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage29.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 5, makeup: true, category: 'applications', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage18.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 6, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage19.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 6, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage21.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 6, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage32.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 6, makeup: false, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage33.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 6, makeup: false, category: 'applications', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage30.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 6, makeup: true, category: 'applications', order: 5, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage15.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 7, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage16.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 7, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage22.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 7, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage25.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 7, makeup: false, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'percentages', filename: 'percentage24.html')
Graph.create!(typ: 'prob', context: 'percentages', batch: 7, makeup: true, category: 'applications', order: 4, file_id: p.id)
#GRAPH TUPLES FROM ./APPLICATIONS/MONEY/graph.txt
t = Theory.find_by!(category: 'applications', context: 'money', filename: 'moneytheory.html')
Graph.create!(typ: 'theory', context: 'money', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'applications')
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money2.html')
Graph.create!(typ: 'prob', context: 'money', batch: 1, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money20.html')
Graph.create!(typ: 'prob', context: 'money', batch: 1, makeup: true, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money1.html')
Graph.create!(typ: 'prob', context: 'money', batch: 2, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money3.html')
Graph.create!(typ: 'prob', context: 'money', batch: 3, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money4.html')
Graph.create!(typ: 'prob', context: 'money', batch: 3, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money21.html')
Graph.create!(typ: 'prob', context: 'money', batch: 3, makeup: true, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money5.html')
Graph.create!(typ: 'prob', context: 'money', batch: 4, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money6.html')
Graph.create!(typ: 'prob', context: 'money', batch: 4, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money22.html')
Graph.create!(typ: 'prob', context: 'money', batch: 4, makeup: true, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money7.html')
Graph.create!(typ: 'prob', context: 'money', batch: 5, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money8.html')
Graph.create!(typ: 'prob', context: 'money', batch: 5, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money23.html')
Graph.create!(typ: 'prob', context: 'money', batch: 5, makeup: true, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money9.html')
Graph.create!(typ: 'prob', context: 'money', batch: 6, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money24.html')
Graph.create!(typ: 'prob', context: 'money', batch: 6, makeup: true, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money10.html')
Graph.create!(typ: 'prob', context: 'money', batch: 7, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money28.html')
Graph.create!(typ: 'prob', context: 'money', batch: 7, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money11.html')
Graph.create!(typ: 'prob', context: 'money', batch: 8, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money25.html')
Graph.create!(typ: 'prob', context: 'money', batch: 8, makeup: true, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money12.html')
Graph.create!(typ: 'prob', context: 'money', batch: 9, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money13.html')
Graph.create!(typ: 'prob', context: 'money', batch: 9, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money14.html')
Graph.create!(typ: 'prob', context: 'money', batch: 9, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money26.html')
Graph.create!(typ: 'prob', context: 'money', batch: 9, makeup: true, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money27.html')
Graph.create!(typ: 'prob', context: 'money', batch: 10, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money19.html')
Graph.create!(typ: 'prob', context: 'money', batch: 10, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money16.html')
Graph.create!(typ: 'prob', context: 'money', batch: 10, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money17.html')
Graph.create!(typ: 'prob', context: 'money', batch: 10, makeup: false, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'money', filename: 'money18.html')
Graph.create!(typ: 'prob', context: 'money', batch: 10, makeup: false, category: 'applications', order: 4, file_id: p.id)
#GRAPH TUPLES FROM ./APPLICATIONS/TIME/graph.txt
t = Theory.find_by!(category: 'applications', context: 'time', filename: 'timetheory.html')
Graph.create!(typ: 'theory', context: 'time', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'applications')
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time1.html')
Graph.create!(typ: 'prob', context: 'time', batch: 1, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time3.html')
Graph.create!(typ: 'prob', context: 'time', batch: 2, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time2.html')
Graph.create!(typ: 'prob', context: 'time', batch: 2, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time13.html')
Graph.create!(typ: 'prob', context: 'time', batch: 2, makeup: true, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time18.html')
Graph.create!(typ: 'prob', context: 'time', batch: 3, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time4.html')
Graph.create!(typ: 'prob', context: 'time', batch: 4, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time5.html')
Graph.create!(typ: 'prob', context: 'time', batch: 4, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time7.html')
Graph.create!(typ: 'prob', context: 'time', batch: 4, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time14.html')
Graph.create!(typ: 'prob', context: 'time', batch: 4, makeup: true, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time6.html')
Graph.create!(typ: 'prob', context: 'time', batch: 5, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time19.html')
Graph.create!(typ: 'prob', context: 'time', batch: 6, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time8.html')
Graph.create!(typ: 'prob', context: 'time', batch: 6, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time20.html')
Graph.create!(typ: 'prob', context: 'time', batch: 6, makeup: true, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time9.html')
Graph.create!(typ: 'prob', context: 'time', batch: 7, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time15.html')
Graph.create!(typ: 'prob', context: 'time', batch: 7, makeup: true, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time17.html')
Graph.create!(typ: 'prob', context: 'time', batch: 8, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time10.html')
Graph.create!(typ: 'prob', context: 'time', batch: 8, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time11.html')
Graph.create!(typ: 'prob', context: 'time', batch: 8, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time12.html')
Graph.create!(typ: 'prob', context: 'time', batch: 8, makeup: false, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time16.html')
Graph.create!(typ: 'prob', context: 'time', batch: 8, makeup: true, category: 'applications', order: 4, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'time', filename: 'time21.html')
Graph.create!(typ: 'prob', context: 'time', batch: 9, makeup: false, category: 'applications', order: 0, file_id: p.id)
#GRAPH TUPLES FROM ./APPLICATIONS/AVERAGE/graph.txt
t = Theory.find_by!(category: 'applications', context: 'average', filename: 'averagetheory.html')
Graph.create!(typ: 'theory', context: 'average', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'applications')
p = Problem.find_by!(category: 'applications', context: 'average', filename: 'average4.html')
Graph.create!(typ: 'prob', context: 'average', batch: 1, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'average', filename: 'average5.html')
Graph.create!(typ: 'prob', context: 'average', batch: 1, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'average', filename: 'average6.html')
Graph.create!(typ: 'prob', context: 'average', batch: 1, makeup: true, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'average', filename: 'average12.html')
Graph.create!(typ: 'prob', context: 'average', batch: 2, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'average', filename: 'average10.html')
Graph.create!(typ: 'prob', context: 'average', batch: 2, makeup: true, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'average', filename: 'average1.html')
Graph.create!(typ: 'prob', context: 'average', batch: 3, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'average', filename: 'average3.html')
Graph.create!(typ: 'prob', context: 'average', batch: 3, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'average', filename: 'average14.html')
Graph.create!(typ: 'prob', context: 'average', batch: 3, makeup: false, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'average', filename: 'average13.html')
Graph.create!(typ: 'prob', context: 'average', batch: 3, makeup: true, category: 'applications', order: 3, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'average', filename: 'average7.html')
Graph.create!(typ: 'prob', context: 'average', batch: 4, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'average', filename: 'average8.html')
Graph.create!(typ: 'prob', context: 'average', batch: 4, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'average', filename: 'average9.html')
Graph.create!(typ: 'prob', context: 'average', batch: 4, makeup: true, category: 'applications', order: 2, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'average', filename: 'average2.html')
Graph.create!(typ: 'prob', context: 'average', batch: 5, makeup: false, category: 'applications', order: 0, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'average', filename: 'average11.html')
Graph.create!(typ: 'prob', context: 'average', batch: 5, makeup: false, category: 'applications', order: 1, file_id: p.id)
p = Problem.find_by!(category: 'applications', context: 'average', filename: 'average15.html')
Graph.create!(typ: 'prob', context: 'average', batch: 5, makeup: true, category: 'applications', order: 2, file_id: p.id)
#GRAPH TUPLES FROM ./INTRODUCTION/example/graph.txt
t = Theory.find_by!(category: 'introduction', context: 'examples', filename: 'exampletheory1.html')
Graph.create!(typ: 'theory', context: 'examples', batch: 0, file_id: t.id, makeup: false, order: 0, category: 'introduction')
t = Theory.find_by!(category: 'introduction', context: 'examples', filename: 'exampletheory2.html')
Graph.create!(typ: 'theory', context: 'examples', batch: 1, file_id: t.id, makeup: false, order: 0, category: 'introduction')
t = Theory.find_by!(category: 'introduction', context: 'examples', filename: 'exampletheory3.html')
Graph.create!(typ: 'theory', context: 'examples', batch: 2, file_id: t.id, makeup: false, order: 0, category: 'introduction')
